package wasi:cli@0.2.0;

interface stdin {
    use wasi:io/streams@0.2.0.{input-stream};
    get-stdin: func() -> input-stream;
}

interface stdout {
    use wasi:io/streams@0.2.0.{output-stream};
    get-stdout: func() -> output-stream;
}
