package wasi:http@0.2.0;

world proxy {
    include wasi:clocks/imports@0.2.0;
    import wasi:random/random@0.2.0;
    import wasi:cli/stdout@0.2.0;
    import wasi:cli/stderr@0.2.0;
    import wasi:cli/stdin@0.2.0;
    import outgoing-handler;

    export incoming-handler;
}
